#!/usr/bin/env python

from __future__ import division, print_function, unicode_literals

"""
A script with tools for computing formation energies
of charged point defects, supporting multiple correction
schemes.
"""

__author__ = "Nils E. R. Zimmermann, Bharat Medasani, Danny Broberg"
__copyright__ = "Copyright 2012, The Materials Project"
__version__ = "1"
__maintainer__ = "Nils E. R. Zimmermann"
__email__ = "n.zimmermann@tuhh.de"
__date__ = "May 1, 2015"

import argparse
import os
import logging
try:
    import yaml
    use_yaml = True
except:
    use_yaml = False

from collections import defaultdict

from monty.serialization import dumpfn, loadfn
from monty.json import MontyEncoder, MontyDecoder

from pymatgen.ext.matproj import MPRester
from pymatgen.core import Element
from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.io.vasp.outputs import Locpot

from pycdt.core.defectsmaker import ChargedDefectsStructures
from pycdt.utils.vasp import make_vasp_defect_files, \
                              make_vasp_dielectric_files
from pycdt.utils.parse_calculations import PostProcess
from pycdt.utils.plotter import  DefectPlotter
from pycdt.utils.log_util import initialize_logging
from pycdt.core.defects_analyzer import DefectsAnalyzer
from pycdt.corrections.finite_size_charge_correction import \
        get_correction_freysoldt, get_correction_kumagai
from pycdt.corrections.kumagai_correction import KumagaiBulkInit



def print_error_message(err_str):
    print("\n================================================================"
        "=============\n\nError: "+err_str)
    print("\n================================================================"
        "=============\n")


def generate_input(args):
    """
    Generates input files for VASP calculations
    The primitive unit cell is obtained from the MP ID provided
    or from structure file pointed at during script call

    Args:
        args (Namespace): contains the parsed command-line arguments for
            this command.
    """

    # initialize variables
    mp_id = args.mp_id
    struct_file = args.struct_file
    mapi_key = args.mapi_key
    nmax = args.nmax
    oxi_state = args.oxi_state
    oxi_range = args.oxi_range
    antisites = args.antisites
    struct_type = args.struct_type
    include_interstitials = args.include_interstitials
    interstitial_elements = args.interstitial_elements
    settings = {}
    if args.input_settings_file:
        if os.path.split(args.input_settings_file)[1] == 'INCAR':
            settings = {'INCAR':{}}
            from pymatgen.io.vasp import Incar
            incar = Incar.from_file(args.input_settings_file)
            settings['INCAR'] = incar
        else:
            settings = loadfn(args.input_settings_file)

    # error-checking
    if not struct_file and not mp_id:
        print_error_message("Neither structure, nor Materials Project " \
                            + "ID (MP-ID) provided!")
        return
    if nmax <= 0:
        print_error_message("maximal number of atoms per supercell"
            " must be larger than zero!")
        return

    # get primitive unit cell
    if mp_id:
        with MPRester(api_key=mapi_key) as mp:
            prim_struct = mp.get_structure_by_material_id(mp_id)

        # transform to conventional unit cell
        conv_struct = SpacegroupAnalyzer( 
                prim_struct).get_conventional_standard_structure()
        make_vasp_dielectric_files(prim_struct, user_settings=settings)
    else:
        conv_struct = Structure.from_file(struct_file)
        make_vasp_dielectric_files(conv_struct, user_settings=settings)

    # manually set oxidation states if those were provided
    oxi_state_dict = {}
    if oxi_state:
        for i in range(len(oxi_state)):
            oxi_state_dict[oxi_state[i][0]] = int(oxi_state[i][1])

    # manually set oxidation-state ranges if those were provided
    oxi_range_dict = {}
    if oxi_range:
        for i in range(len(oxi_range)):
            oxi_range_dict[oxi_range[i][0]] = tuple(
                    [int(oxi_range[i][1]), int(oxi_range[i][2])])

    # Substitution defects if those were provided
    substitutions = {}
    if args.substitutions:
        for i, sub in enumerate(args.substitutions):
            substitutions[sub[0]] = sub[1:]

    # finally, generate VASP input files for defect calculations
    def_structs = ChargedDefectsStructures(
            conv_struct, max_min_oxi=oxi_range_dict, 
            oxi_states=oxi_state_dict, antisites_flag=antisites,
            substitutions=substitutions,
            include_interstitials=include_interstitials,
            interstitial_elements=interstitial_elements,
            cellmax=nmax, struct_type=struct_type)
    make_vasp_defect_files(
            def_structs.defects,
            conv_struct.composition.reduced_formula, 
            user_settings=settings)


def parse_output(args):
    """
    Parses output files from VASP calculations

    Args:
        args (Namespace): contains the parsed command-line arguments for
            this command.
    """

    # initialize variables
    mp_id = args.mp_id
    mapi_key = args.mapi_key
    root_fldr = args.root_fldr

    # error-checking;
    if not mp_id:
        print_error_message("No Materials Project structure ID provided! "
                            "(proceeding anyway)")
        #return
        mp_id = None

    formula = os.path.split(os.path.abspath(root_fldr))[-1]
    initialize_logging(filename=formula+'_parser.log')

    # parse results to get defect data and correction terms
    defect_data = PostProcess(root_fldr, mp_id, mapi_key).compile_all()

    # need to doctor up chemical potentials for dumpfn due to issue with
    # Element not interpretted by MontyEncoder
    defect_data['mu_range'] = {ckey:{k.symbol:v for k,v in cdict.items()}
                               for ckey, cdict in defect_data['mu_range'].items()}

    dumpfn(defect_data, args.defect_data_file_name, cls=MontyEncoder, indent=2)


def compute_corrections(args):
    """
    TODO : Include option for printing pot. plots to defect files,
            rather than main directory
    ----------
    Computes corrections for the charged point defects
    Supported: Isotropic Freysoldt method, Extended Freysoldt method (Kumagai)

    Args:
        args (Namespace): contains the parsed command-line arguments for
            this command.
    """


    # initialize variables
    defect_data_file_name = args.defect_data_file_name
    corrections_file_name = args.corrections_file_name
    plot_results = args.plot_results
    correction_method = args.correction_method

    # parse results to get defect data and correction terms
    defect_data = loadfn(defect_data_file_name, cls=MontyDecoder)
    if args.epsilon:
        epsilon = args.epsilon
    else:
        epsilon = defect_data['epsilon']

    bulk = defect_data['bulk_entry']
    bulk_structure = bulk.structure
    defects = defect_data['defects']
    corrections = defaultdict(list)

    formula = bulk.composition.reduced_formula
    initialize_logging(filename=formula+'_correction.log')

    #loading locpot object now is useful for both corrections
    print ('loading bulk locpot for corrections')
    blklpt = Locpot.from_file(bulk.data['locpot_path']) 
    if correction_method == 'freysoldt':
        for defect in defects:
            print ('defect_name: ', defect.full_name)
            print ('-----------------------------------------\n\n')
            correction, blklpt = get_correction_freysoldt(
                    defect, blklpt, epsilon, title=defect.full_name,
                    defpos = defect.site)
            defect.charge_correction = correction
            corrections[defect.name].append({
                'charge_correction': correction, 'charge':defect.charge})
    elif correction_method == 'kumagai':
        locpot_path_blk = bulk.data['locpot_path']
        path_blk = os.path.split(locpot_path_blk)[0]
        encut = bulk.data['encut']
        kumagai_init = KumagaiBulkInit(blklpt.structure, blklpt.dim, epsilon,
                                       encut, tolerance=0.0001)
        for defect in defects:
            print ('defect_name: ', defect.full_name)
            print ('-----------------------------------------\n\n')
            correction = get_correction_kumagai(
                    defect, path_blk, kumagai_init, bulk_locpot=blklpt,
                    title=defect.full_name, defpos = defect.site)
            defect.charge_correction = correction
            corrections[defect.name].append({
                    'charge_correction': correction, 'charge': defect.charge})
    else:
        print ('Invalid correction method: ',correction_method,'. Select either ' \
               '"freysoldt" or "kumagai"')

    dumpfn(corrections, corrections_file_name, cls=MontyEncoder, indent=2)


def compute_formation_energies(args):
    """
    Computes transition levels and plots formation energy
    of charged point defects across the band gap

    Args:
        args (Namespace): contains the parsed command-line arguments for
            this command.
    """

    # initialize variables
    defect_data_file_name = args.defect_data_file_name
    corrections_file_name = args.corrections_file_name

    # parse results to get defect data and correction terms
    defect_data = loadfn(defect_data_file_name, cls=MontyDecoder)
    defects = defect_data['defects']

    formula = defect_data['bulk_entry'].structure.composition.reduced_formula
    initialize_logging(filename=formula+'_formation_energy.log')

    if os.path.isfile(corrections_file_name):
        correction_data = loadfn(corrections_file_name)  
        for computed_defect in defects:
            name_def = computed_defect.name
            q = computed_defect.charge
            for entry in correction_data[name_def]:
                if q == entry['charge']:
                    correction = entry['charge_correction']
                    break
            computed_defect.charge_correction = correction
    elif corrections_file_name == "corrections.json":  # Default filename
        pass # Don't bother, the user is not worried about corrections
    else:
        raise OSError([2, "File not found", corrections_file_name])

    # Gap
    if not args.bandgap:
        bandgap = defect_data['gap']
    else:
        bandgap = args.bandgap

    vbm = defect_data['vbm']
    blk_entry = defect_data['bulk_entry']
    mu_range = defect_data['mu_range']

    #doctor up mu_range because of cls Monty Decoder issue with Element
    mu_range = {ckey:{Element(k):v for k,v in cdict.items()}
                               for ckey, cdict in mu_range.items()}

    for region, mu in mu_range.items():
        da = DefectsAnalyzer(blk_entry, vbm, mu, bandgap)
        for defect in defects:
            da.add_computed_defect(defect)

        if region == list(mu_range.keys())[0]:
            da_trans = da.get_transition_levels()
            if use_yaml:
                with open('transition_levels.yaml', 'w') as f:
                    yaml.dump(da_trans, f)
            print ("============\nDefect Transition Levels (eV):\n===========")
            for dfct_name, trans_lvls in da_trans.items():
                print (dfct_name)
                ky_vals = sorted(trans_lvls.items(), key=lambda x: x[0][0])
                for qpair, trans_lvl in ky_vals:
                    print ("{}: {}".format(qpair, trans_lvl))

        if args.plot_results:
            plotter = DefectPlotter(da)
            form_en_plot = plotter.get_plot_form_energy()
            form_en_plot.savefig(
                    region+'_region_defect_form_energy.'+args.file_format, 
                    bbox_inches='tight')
            print('printed ',region,' plot')


def main():
    parser = argparse.ArgumentParser(description="""
        PyCDT is a script that generates vasp input files, parses vasp output
        files, and computes the formation energy of charged defects.
        This script works based on several sub-commands with their own options.
        To see the options for the sub-commands, type
        "pycdt sub-command -h".""",
        epilog="""
        Authors: N. E. R. Zimmermann, B. Medasani, D. Broberg, G. Hautier
        Version: {}
        Last updated: {}""".format(__version__, __date__))


    subparsers = parser.add_subparsers()
    struct_string = "Input structure. Can accept multiple file formats. " \
        "Supported formats include CIF, POSCAR/CONTCAR, CHGCAR, LOCPOT, "\
        "vasprun.xml, CSSR, Netcdf and pymatgen's JSON serialized structures."
    mp_id_string = "Materials Project id of the structure.\nFor more info on " \
        "Materials Project, please, visit www.materialsproject.org."
    mapi_string = "Your Materials Project REST API key.\nFor more info, " \
        "please, visit www.materialsproject.org/open."
    nmax_string = "Maximum number of atoms in supercell.\nThe default is" \
        " 128.\nKeep in mind that the number of atoms in the supercell may" \
        " vary from the provided number including the default."
    oxi_state_string = "Oxidation state for an element.\nTwo arguments" \
        " are expected: the element type for which the oxidation state is" \
        " to be specified and the oxidation state (e.g., --oxi_state As -3)."
    oxi_range_string = "Oxidation range for an element.\nThree arguments" \
        " are expected: the element type for which the oxidation state range is" \
        " to be specified as well as the lower and the upper limit of the" \
        " range (e.g., --oxi_range As -3 5)."
    struct_type_string = "Structure type to determine the charge range" \
        " for the defects. Valid options are 'semiconductor' and 'insulator'"\
        " With 'semiconductor' option, the defect charges are determined by"\
        " database approach where defect charges found in literature for"\
        " common semiconductors.\nFor 'insulator' option, a conservative"\
        " approach is used. For cations, the oxidation states of (0, A) are"\
        " considered, where A is the cation oxidation in the compound."\
        " Similarly for anions, (-B, 0) where -B is the oxidation state of"\
        " anion in the compound."
    no_antisites_string = "Optional flag to indicate that anti-site defects" \
        " should not be generated."
    include_interstitials_string = "Optional flag to indicate that" \
        " interstitial defects should be generated. If you do not provide" \
        " positional\narguments, intrinsic interstitials are set-up as" \
        " per\ndefault.  Providing positional arguments (elemental\n" \
        "symbols) enables the set-up of specific interstitials."
    interstitial_elements_string = "Explicit list of elements" \
        " that are to be considered for interstitial generation. " \
        " If no elements are given, intrinsic interstitials" \
        " are considered."
    substitutions_string = "Substitutional defects (optional) to be generated.\n" \
        " Minimum of two arguments are expected: the element on which the " \
        " substitution is to applied as well as the substitution elements " \
        " (e.g., --sub As P N O)."
    input_settings_string = "Supply VASP input settings for INCAR, KPOINTS in" \
        " the specified YAML/JSON file."
    root_fldr_string = "Path (relative or absolute) to directory" \
        " in which data of charged point-defect calculations for" \
        " a particular system are to be found.  Default is the" \
        " current working directory."
    defect_data_file_name_string = "Name of output file for defect data" \
        " obtained from parsing VASP's files of charged-defect" \
        " calculations in json format.\nDefault is" \
        " \"defect_data.json\"; \"None\" suppresses output."
    corrections_file_name_string = "Name of output file for data on" \
        " correction terms to formation energies of charged defects" \
        " in json format.\nDefault is \"corrections.json\";" \
        " \"None\" suppresses output."
    plot_results_string = "Optional flag to indicate that results" \
        " should be plotted."
    epsilon_string = "Optional: provide a dielectric constant to be" \
        " used in the correction terms of the defect-formation energies.\n" \
        "Only a scalar is accepted.\nIf not provided, the dielectric" \
        " constant is extracted from the corresponding VASP calculation.\n" \
        "Note that this evaluation script expects the dielectric" \
        " constant calculation to have been performed to properly analyze" \
        " the data."
    correction_string = "Method to be used to compute finite size charge " \
        "correction for the defect-formation energies.\n" \
        "Options are `freysoldt' and `kumagai'.\n" \
        "If not provided, Freysoldt method is assumed." 
    bandgap_string = "User defined band gap to plot the defect formation " \
        "energies.\nBy default, Materials Project (MP) bandgap is " \
        "used.\nHowever, MP bandgap could be a severly underpredicted value." 
    plot_format_string = "User defined file format to store the defect formation " \
        "energies plot.\nBy default, 'eps' formation is used.\nSupported" \
        "options are png, eps, jpg." 


    parser_input_files = subparsers.add_parser(
            "generate_input",
            help="Generates Vasp input files for charged point defects.")
    parser_input_files.add_argument("-s", "--structure_file", default=None, 
                                    dest="struct_file", help=struct_string) 
    parser_input_files.add_argument("-i", "--mpid", default=None,
                                    type=str.lower, dest="mp_id", 
                                    help=mp_id_string)
    parser_input_files.add_argument("-k",  "--mapi_key", default=None,
                                    dest="mapi_key", help=mapi_string)
    parser_input_files.add_argument("-n", "--nmax", type=int, default=80,
                                    dest="nmax", help=nmax_string)
    parser_input_files.add_argument("-or", "--oxi_range", action='append',
                                    type=str, nargs=3, dest="oxi_range",
                                    help=oxi_range_string)
    parser_input_files.add_argument("-os", "--oxi_state", action='append',
                                    type=str, nargs=2, dest="oxi_state",
                                    help=oxi_state_string)
    parser_input_files.add_argument("-t", "--type", default="semiconductor",
                                    type=str, dest="struct_type", 
                                    help=struct_type_string)
    parser_input_files.add_argument("-noa", "--no_antisites",
                                    action='store_false', dest="antisites",
                                    help=no_antisites_string)
    parser_input_files.add_argument("-a", "--antisites",
                                    action='store_true', dest="antisites",
                                    help=no_antisites_string)
    parser_input_files.add_argument("-ii", "--include_interstitials",
                                    action='store_true', 
                                    dest="include_interstitials",
                                    help=include_interstitials_string)
    parser_input_files.add_argument("interstitial_elements", type=str,
                                    default=[], nargs="*", \
                                    help=interstitial_elements_string)
    parser_input_files.add_argument("--sub", action='append', type=str,
                                    nargs="+", dest='substitutions',\
                                    help=substitutions_string)
    parser_input_files.add_argument("-is", "--input_settings_file", 
                                    type=str, default=None,
                                    dest="input_settings_file",
                                    help=input_settings_string)
    parser_input_files.set_defaults(func=generate_input)

    os_path_abspath_this = os.path.abspath(".")
    parser_vasp_output = subparsers.add_parser(
            "parse_output",
            help="Parses VASP output for calculation of formation energies of"
                " charged point defects.")
    parser_vasp_output.add_argument("-i", "--mpid", type=str.lower,
                                    dest="mp_id", help=mp_id_string)
    parser_vasp_output.add_argument("-k", "--mapi_key", default=None,
                                    dest="mapi_key", help=mapi_string)
    parser_vasp_output.add_argument("-d", "--directory",
                                    default=os_path_abspath_this,
                                    dest="root_fldr",
                                    help=root_fldr_string)
    parser_vasp_output.add_argument("-o", "--output_file_name",
                                    default="defect_data.json",
                                    dest="defect_data_file_name",
                                    help=defect_data_file_name_string)
    parser_vasp_output.set_defaults(func=parse_output)

    parser_compute_corrections = subparsers.add_parser(
            "compute_corrections",
            help="Computes correction for finite size supercell error "
            "associated with charged point defects.")
    parser_compute_corrections.add_argument("-i", "--input_file_name",
                                            default="defect_data.json",
                                            dest="defect_data_file_name",
                                            help=defect_data_file_name_string)
    parser_compute_corrections.add_argument("-o", "--output_file_name",
                                            default="corrections.json",
                                            dest="corrections_file_name",
                                            help=corrections_file_name_string)
    parser_compute_corrections.add_argument("-p", "--plot_results",
                                            action='store_true',
                                            dest="plot_results",
                                            help=plot_results_string)
    parser_compute_corrections.add_argument("-e",  "--epsilon", type=float, 
                                            default=None, dest="epsilon",
                                            help=epsilon_string)
    parser_compute_corrections.add_argument("-c", "--correction_method",
                                            type=str, default="freysoldt",
                                            dest="correction_method",
                                            help=correction_string)
    parser_compute_corrections.set_defaults(func=compute_corrections)

    parser_compute_energies = subparsers.add_parser(
            "compute_formation_energies",
            help="Computes formation energies of charged point defects from "
            "the parsed VASP output.")
    parser_compute_energies.add_argument("-i", "--input_file_name",
                                         default="defect_data.json",
                                         dest="defect_data_file_name",
                                         help=defect_data_file_name_string)
    parser_compute_energies.add_argument("-c", "--corrections_file_name",
                                         default="corrections.json",
                                         dest="corrections_file_name",
                                         help=corrections_file_name_string)
    parser_compute_energies.add_argument("-p", "--plot_results",
                                         action='store_true',
                                         dest="plot_results",
                                         help=plot_results_string)
    parser_compute_energies.add_argument("-bg", "--bandgap",
                                         type=float, default=0, dest="bandgap",
                                         help=bandgap_string)
    parser_compute_energies.add_argument("-f", "--format", default='eps',
                                         dest="file_format",
                                         help=plot_format_string)
    parser_compute_energies.set_defaults(func = compute_formation_energies)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
